Cred

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -67,12 +67,18 @@ agent any
 		stage ('Username Password Credential'){
 		steps { 
 		withCredentials([
-			usernamePassword(credentialsId: 'user-pass-test',
-					usernameVariable: '$janav',
-					passwordVariable:'PASSWORD')
+			usernamePassword(
+					credentialsId: 'user-pass-test',
+					usernameVariable: 'janav',
+					passwordVariable:'PASSWORD'
+			)
 		]) {
 
-                    sh 'if [ -n "$USERNAME" ]&& [-n "$PASSWORD"]; then echo "Credential is available"; else echo "Credential is missing"; exit 1 fi'
+                    sh '''
+		if [ -n "$janav" ] && [-n "$PASSWORD"]; 
+		then echo "Credential is available";
+		 else echo "Credential is missing"; exit 1 
+			fi'''
 						}
 					}
 			}
